### ISSUE TITLE
Why @netflix/nerror?

### ISSUE THREAD

**Issue by sergiz** [restify/errors#103]
https://github.com/restify/errors/commit/a37b7f00e962f2ec5b4a827a9df22d44a5df2147

Is there any technical reason why this package depends on @netflix/nerror and not on the original verror?
restify-errors is literally the only public package that depends on nerror, so it forces us to install nerror, besides verror that many of us (indirectly) use already anyway.

**Comment by retrohacker** [comment]
Heya @sergiz. `verror` had parsing/serialization bugs (particularly around improperly handling `%` in error messages IIRC) that caused production issues for us. The edge cases where these would trigger were rare, which made them particularly hairy to debug and work around.

We attempted to upstream our fixes into `verror` proper but that didn't work out so we've decided to maintain our own version of the module moving forward.
