### ISSUE TITLE
Update to latest assert-plus

### ISSUE THREAD

**Issue by BryanDonovan** [restify/errors#15]
Hi, 

Can you please update to the latest assert-plus npm (currently 0.2.0)?  It fixes an issue I see in my code when I try to run in strict mode (I'm trying to update my code and its dependencies to work with node 5.0.0 in strict mode to get access to ECMAScript 6 features).  This issue occurs when assert-plus's `assert.string()` method is called.

```
 /tmp/errors(master) $ node --use_strict foo.js
/private/tmp/errors/node_modules/assert-plus/assert.js:41
                stackFunc = stackFunc || _assert.caller;
                                                ^

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at _assert (/private/tmp/errors/node_modules/assert-plus/assert.js:41:49)
    at Object.string (/private/tmp/errors/node_modules/assert-plus/assert.js:160:9)
    at Object.<anonymous> (/private/tmp/errors/foo.js:2:8)
```

**Comment by DonutEspresso** [comment]
3.1.0 has been published with the new assert-plus.

**Comment by BryanDonovan** [comment]
thanks!
