### ISSUE TITLE
Does not follow previous conventions of Restify

### ISSUE THREAD

**Issue by nodesocket** [restify/errors#28]
Using this new module:

```javascript
return next(new errors.BadRequestError('400 bad request message here'));
```
Returns the following JSON:

```
{"code":"BadRequest","message":"400 bad request message here"}
```

Previously, using Restify:

```javascript
return next(new restify.BadRequestError('400 bad request message here'));
```

Returned the following JSON:

````
{
    "message": "/foo does not exist",
    "statusCode": 404,
    "body": {
        "code": "ResourceNotFound",
        "message": "/foo does not exist"
    },
    "restCode": "ResourceNotFound"
}
````

I actually don't care about the `body` property, but `statusCode` and `restCode` are useful, and should be named the same key.

**Comment by nodesocket** [comment]
Any update on this?

**Comment by DonutEspresso** [comment]
Hi @nodesocket, to update the convo I suspect you may have a custom JSON formatter that is returning the full key set of the error object. The default formatter returns _only_ the `body` property. Can you confirm?

**Comment by nodesocket** [comment]
Sorry for the delay responding.

Correct, using a custom JSON formatter of:

```javascript
_server = restify.createServer({
        formatters: {
            'application/json': function(req, res, body, callback) {
                return callback(null, JSON.stringify(body, null, 4));
            }
        }
    });
```

**Comment by DonutEspresso** [comment]
Gotcha, that would do it. restify's default serializer used to do serialization for the error objects, that's now been offloaded to restify-errors' `toJSON()` method. Out of the box serialization hasn't changed for restify users. You've been seeing the full output cause you had your own serializer. If you want the full output, I'd recommend doing an `body instanceof Error` check, and then copying the properties that you want exposed. 

Alternatively, if your errors are inheriting from restify-errors, you can specify a custom `toJSON()` when you call `makeConstructor()`.

**Comment by DonutEspresso** [comment]
This appears to be resolved, let us know if you're still seeing issues.
