### ISSUE TITLE
toString doesn not print caused by: ...

### ISSUE THREAD

**Issue by jonathan-rodan** [restify/errors#30]
I was trying to create an error handler and noticed that toString wasn't working properly (or at least not as documented).

```
const internalError = new errors.NotFoundError('NotFoundError message');
const outerError = new errors.UnauthorizedError(internalError, 'UnauthorizedError message');

console.log(outerError.toString());
// UnauthorizedError: UnauthorizedError message

console.log(outerError.message);
// UnauthorizedError message

console.log(outerError);
/*
{ [UnauthorizedError: UnauthorizedError message]
  message: 'UnauthorizedError message',
  we_cause: 
   { [NotFoundError: NotFoundError message]
     message: 'NotFoundError message',
     body: { code: 'NotFound', message: 'NotFoundError message' },
     context: null },
  body: { code: 'Unauthorized', message: 'UnauthorizedError message' },
  context: null }
*/
```

The documentation describes

<img width="914" alt="screen shot 2016-04-07 at 11 21 51 am" src="https://cloud.githubusercontent.com/assets/1568357/14356479/10b3b382-fcb3-11e5-83a3-a48e1cdea4c4.png">

I can create a pull request, but I don't want to do it without knowing what to change the toString or the documentation.

If you prefer to update the docs, I'd like to create a `messageWithCause()` function that keeps the `caused by`.

**Comment by DonutEspresso** [comment]
Thanks for the report! This is definitely a bug. Looks like it was introduced with #18. The original `toString()` behavior should be using whatever was provided by VError, that PR stomped on that behavior. I think we want the original VError behavior for `toString()`, but will probably keep the existing `toJSON()` behavior.

**Comment by jonathan-rodan** [comment]
I'll work on a pull request as soon as I get some free time. It might take me a few days.

**Comment by DonutEspresso** [comment]
@jonathan-rodan, did you ever get started on this yet? If not, I've got a branch ready to go - we're looking to cut 5.x restify soon and want to get this fixed before then. Appreciate the help!

**Comment by jonathan-rodan** [comment]
Yes, The change was really simple. I'm not in my computer. Will push tomorrow.
