### ISSUE TITLE
Question: best way to override .toString() or how to expose additional json object on details

### ISSUE THREAD

**Issue by paul42** [restify/errors#32]
I wanted to create an additional property on the return, but I can't quite figure out the correct syntax for makeContructor(name, defaults) to get the toString and toJson to update - I'd like to ideally pass in an object, and then strip off a property off that object (errors) and perform some work on it (getting message for each object in errors) and just combine them.

ideally, could I submit a PR that did something like https://github.com/Raynos/send-data
https://github.com/Raynos/send-data/blob/master/error.js#L78-L82

        if (opts.additionalParams) {
        opts.additionalParams.forEach(function appendKey(k) {
            body[k] = err[k];
        });
    }

the reason I ask is right now options.context sends back the information in logging, but I don't have a way to get that options.context out to the user.

Thanks in advance,
Paul

**Comment by paul42** [comment]
ideally, could I submit a PR that did something like https://github.com/Raynos/send-data
https://github.com/Raynos/send-data/blob/master/error.js#L78-L82
        if (opts.additionalParams) {
        opts.additionalParams.forEach(function appendKey(k) {
            body[k] = err[k];
        });
    }

**Comment by DonutEspresso** [comment]
Hi @paul42 , you can override the default toString() method by simply passing it in when you create your error. For example, if you wanted to just return the message, you can do this:

```js
restifyErrs.makeConstructor('FooError', {
  toString: function() { 
    return this.message;
 }
});
```

You can then return an arbitrary bucket of properties off the error object.

**Comment by DonutEspresso** [comment]
Haven't heard back in awhile - going to close the issue. If you still have issues please let us know.
