### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by kennethkoontz** [restify/errors#39]
Is there a way to render multiple errors or accomplish the following in the response.

```json
{
  "message": "Validation Error",
  "errors": [
    { "message": "`email` is required." },
    { "message": "`first_name` is required." },
  ]
}
```

**Comment by DonutEspresso** [comment]
If you have an array of error objects, you'd probably just want to write your own JSON serializer before calling `res.send`:

```js
var errs = [err1, err2];
res.send(customSerializer(errs));
```

Alternatively, if it's a VError or MultiError, you can overwrite the default JSON serializer and check for instance of Error, and just crawl through the nested causes and format them any way you'd like.

**Comment by kennethkoontz** [comment]
Thanks!
