### ISSUE TITLE
Replace util.inherits

### ISSUE THREAD

**Issue by yan-foto** [restify/errors#61]
Both `HttpError` and `RestError` objects use [`util.inherit`](https://nodejs.org/docs/latest/api/util.html#util_util_inherits_constructor_superconstructor) to establish (pseudo)inheritance. As stated by the docs:

> usage of `util.inherits()` is discouraged. Please use the ES6 class and extends keywords to get language level inheritance support.

**Comment by DonutEspresso** [comment]
Thanks! As we phase out node 0.12 support we'll definitely want to move to using ES6 classes.
