### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by royibernthal** [restify/errors#62]
Are there any typescript typing anywhere for restify-errors?

I can see in the DefinitelyTyped repo only typings for restify (not for beta though) and for restify-plugins.

If there isn't one, would it be possible for you to create one?

**Comment by stevehipwell** [comment]
`npm install --save-dev @types/restify-errors`

**Comment by simonepri** [comment]
@retrohacker maybe we can add a reference to this into the readme?
