### ISSUE TITLE
is there a way to pass more information with the error

### ISSUE THREAD

**Issue by pkyeck** [restify/errors#63]
tried to do something like this:

```javascript
throw new errors.UnprocessableEntityError({
  message: 'email invalid',
  somethingElse: 'maybe some more info'
});
```

but restify's output stays the same:

```json
{
  "code": "UnprocessableEntity",
  "message": "email invalid"
}
```

**Comment by DonutEspresso** [comment]
Hello, this has more to do with restify's formatters than the error module itself. You'll basically want to create an application/json formatter that serializes the error into a format that you're expecting. You can use the example here to do something similar:
http://restify.com/#content-negotiation

Basically, check if the body is `instanceof Error`, then send a POJO with the things you'd like to have sent to the client.

**Comment by pkyeck** [comment]
thanks for pointing me in the right direction ... 👍
