### ISSUE TITLE
Custom Body in rest and http errors

### ISSUE THREAD

**Issue by gthicks** [restify/errors#72]
In the process of migrating from Restify 4 to Restify 5, it seems that we are no longer able to override the body of the error.

You used to be able to do:
`new restify.errors.BadRequestError({body: {whatever: 'you want'}})`

After looking through the documentation and the source code, I can't see a way to accomplish this. Is this something that would fit in this project? I would be willing to open a PR if I knew it would be well received. 

Thanks, Garret

**Comment by simonepri** [comment]
Hi @gthicks , I've faced the same problem.
I've just realized an npm module in order to overcome to this.
It's called [`restify-errors-options`](https://www.npmjs.com/package/restify-errors-options).

https://github.com/simonepri/restify-errors-options

Your example simply becomes:
```
errorsOptions.add('whatever');
new restify.errors.BadRequestError({body: {whatever: 'you want'}});
```

**Comment by simonepri** [comment]
@ltvolks @retrohacker  What do you think to add a section documenting this behaviour?
My suggestion is to add a reference to `restify-errors-options` while a better solution will be found.
`restify-errors-options` also allows users to provide defaults for custom values added.

Like that:

```
function defaultErrno(code) {
    return code.split('').filter(c => c === c.toUpperCase()).join('') + 'E';
}
errorsOptions.add('errno', defaultErrno);

const err = new errors.BadRequestError();
err.toJSON();
//=> {code: 'BadRequest', message: '', errno: 'BRE'}

err = new errors.NotFoundError();
err.toJSON();
//=> {code: 'NotFound', message: '', errno: 'NFE'}

err = new errors.InternalError({errno: 'IE.001231.231231'});
err.toJSON();
//=> {code: 'NotFound', message: '', errno: 'E.001231.231231'}
```

This allows users to create modularized options and publish them for others, like this one:
https://github.com/simonepri/restify-errors-options-errno

**Comment by DonutEspresso** [comment]
I can shed some context on this. In 4.x and previous versions of restify, each of the default formatters treated errors as a special entity. For example, in the JSON formatter, the code looked something like:

```js
if (dataToSend instanceof Error) { ... } else { ... }
```

This was repeated across all the formatters. In 5.x we made the shift towards formatters not doing any type of magic based on inspection of payload. Instead, the JSON formatter now just does:

```js
return JSON.stringify(dataToSend);
```

This means that to define the structure of the payload, one can define `toJSON()` for that object. What we wanted to achieve was separation of the construction of the object (in this case, the error) from how it would be serialized. In the case of any error or custom error created via restify-errors, that behavior is defined here:
https://github.com/restify/errors/blob/master/lib/baseClasses/HttpError.js#L131

With that in mind, the best way to do this today is to hook into the `restifyError` event that is emitted by the server:

```js
server.on('restifyError', function(req, res, err, callback) {
    err.toJSON = function customToJSON() {
        return {
            name: err.name,
            mesg: err.message
        };
    };
    return callback();
});

server.on('restifyError', function(req, res, err, callback) {
    err.toJSON = function customToJSON() {
        return 'i just want a string';
    };
    return callback();
});
````

As I type this I noticed the documentation is actually _incorrect_ - we'll have that fixed shortly!

**Comment by DonutEspresso** [comment]
One minor note - if you only want to change the values of the existing message, but not the structure, i.e., you are ok with the default `toJSON()` fields, you can simply pass your custom values into the constructor:
https://github.com/restify/errors#customizing-errors

Regarding the addition of arbitrary properties on errors, we facilitate that using the `context` option of the restify-error constructor object:
https://github.com/restify/errors#bunyan-support

You would just want to make sure you are using the `context` field as part of your custom `toJSON()` implementation.

**Comment by retrohacker** [comment]
Should have been shipped in #1439

**Comment by retrohacker** [comment]
Hey @simonepri,

Thank you for engaging so much on this repo! Want to be a maintainer? :smile:

If so, shoot me an email and we can chat: william.jblankenship@gmail.com

**Comment by simonepri** [comment]
Glad to!
Thanks to all of you for the fantastic job with Restify!
