### ISSUE TITLE
cannot compare error using instanceof

### ISSUE THREAD

**Issue by seoker** [restify/errors#81]
Based on README, the error should be compared using `instanceof` operator.

for example
```javascript
const errors = require('restify-errors');
const err = new errors.ResourceNotFoundError();
err instanceof errors.ResourceNotFoundError; // true
```

However I couldn't compare them in a specific case under `restify`:
```javascript
// trigger this error when some in-existing route being called
server.on('NotFound', (req, res, err, cb) => {
  req.log.info(JSON.stringify(err, null, 2)); // { "code": "ResourceNotFound", "message": "/xxxx does not exist" }
  req.log.info(err.toString()); // ResourceNotFoundError: /xxxx does not exist
  req.log.info(err.code); // Error
  if (err instanceof errors.ResourceNotFoundError) {
    // never get here
  }

  cb();
});

```

kind of weird, any ideas?
I'm not sure where is better to report this issue, `restify` or this repo?

**versions**
`restify`: `5.2.0`
`restify-errors`: `5.0.0`

**Comment by seoker** [comment]
Had opened an issue at restify/restify#1496

**Comment by DonutEspresso** [comment]
Thanks for bringing this our attention! Let's keep the convo going at restify/node-restify#1496
